In [1]:
#importing the libraries

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
#importing the dataset

data=pd.read_csv("kidney_disease.csv")

In [3]:
data  

id   age    bp     sg   al   su     rbc        pc         pcc  \
0      0  48.0  80.0  1.020  1.0  0.0     NaN    normal  notpresent   
1      1   7.0  50.0  1.020  4.0  0.0     NaN    normal  notpresent   
2      2  62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent   
3      3  48.0  70.0  1.005  4.0  0.0  normal  abnormal     present   
4      4  51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent   
..   ...   ...   ...    ...  ...  ...     ...       ...         ...   
395  395  55.0  80.0  1.020  0.0  0.0  normal    normal  notpresent   
396  396  42.0  70.0  1.025  0.0  0.0  normal    normal  notpresent   
397  397  12.0  80.0  1.020  0.0  0.0  normal    normal  notpresent   
398  398  17.0  60.0  1.025  0.0  0.0  normal    normal  notpresent   
399  399  58.0  80.0  1.025  0.0  0.0  normal    normal  notpresent   

             ba  ...  pcv    wc   rc  htn   dm  cad appet   pe  ane  \
0    notpresent  ...   44  7800  5.2  yes  yes   no  good   no   no   
1    notpresent  ...   38  6000  NaN   no   no   no  good   no   no   
2    notpresent  ...   31  7500  NaN   no  yes   no  poor   no  yes   
3    notpresent  ...   32  6700  3.9  yes   no   no  poor  yes  yes   
4    notpresent  ...   35  7300  4.6   no   no   no  good   no   no   
..          ...  ...  ...   ...  ...  ...  ...  ...   ...  ...  ...   
395  notpresent  ...   47  6700  4.9   no   no   no  good   no   no   
396  notpresent  ...   54  7800  6.2   no   no   no  good   no   no   
397  notpresent  ...   49  6600  5.4   no   no   no  good   no   no   
398  notpresent  ...   51  7200  5.9   no   no   no  good   no   no   
399  notpresent  ...   53  6800  6.1   no   no   no  good   no   no   

    classification  
0              ckd  
1              ckd  
2              ckd  
3              ckd  
4              ckd  
..             ...  
395         notckd  
396         notckd  
397         notckd  
398         notckd  
399         notckd  

[400 rows x 26 columns]

In [4]:
data.isnull().any() #checking for missing values


id                False
age                True
bp                 True
sg                 True
al                 True
su                 True
rbc                True
pc                 True
pcc                True
ba                 True
bgr                True
bu                 True
sc                 True
sod                True
pot                True
hemo               True
pcv                True
wc                 True
rc                 True
htn                True
dm                 True
cad                True
appet              True
pe                 True
ane                True
classification    False
dtype: bool

In [62]:
data['age']=data['age'].fillna(value=data['age'].mean())

In [63]:
data['bp']

0      80.0
1      50.0
2      80.0
3      70.0
4      80.0
       ... 
395    80.0
396    70.0
397    80.0
398    60.0
399    80.0
Name: bp, Length: 400, dtype: float64

In [7]:
data['sg']=data['sg'].fillna(value=data['sg'].mean())

In [8]:
data['al']=data['al'].fillna(value=data['al'].mean())

In [9]:
data['su']=data['su'].fillna(value=data['su'].mean())

In [10]:
data['rbc']=data['rbc'].fillna(value=data['rbc'].mode().iloc[0])

In [11]:
data['pc']=data['pc'].fillna(value=data['pc'].mode().iloc[0])

In [12]:
data['pcc']=data['pcc'].fillna(value=data['pcc'].mode().iloc[0])

In [13]:
data['ba']=data['ba'].fillna(value=data['ba'].mode().iloc[0])

In [14]:
data['bgr']=data['bgr'].fillna(value=data['bgr'].mean())

In [15]:
data['bu']=data['bu'].fillna(value=data['bu'].mean())

In [16]:
data['sc']=data['sc'].fillna(value=data['sc'].mean())

In [17]:
data['sod']=data['sod'].fillna(value=data['sod'].mean())

In [18]:
data['pot']=data['pot'].fillna(value=data['pot'].mean())

In [19]:
data['hemo']=data['hemo'].fillna(value=data['hemo'].mean())

In [20]:
data['pcv']=data['pcv'].fillna(value=data['pcv'].mode().iloc[0])

In [21]:
data['wc']=data['wc'].fillna(value=data['wc'].mode().iloc[0])

In [22]:
data['rc']=data['rc'].fillna(value=data['rc'].mode().iloc[0])

In [23]:
data['htn']=data['htn'].fillna(value=data['htn'].mode().iloc[0])

In [24]:
data['dm']=data['dm'].fillna(value=data['dm'].mode().iloc[0])

In [25]:
data['cad']=data['cad'].fillna(value=data['cad'].mode().iloc[0])

In [26]:
data['appet']=data['appet'].fillna(value=data['appet'].mode().iloc[0])

In [27]:
data['pe']=data['pe'].fillna(value=data['pe'].mode().iloc[0])

In [28]:
data['ane']=data['ane'].fillna(value=data['ane'].mode().iloc[0])

In [29]:
data.isnull().any()

id                False
age               False
bp                False
sg                False
al                False
su                False
rbc               False
pc                False
pcc               False
ba                False
bgr               False
bu                False
sc                False
sod               False
pot               False
hemo              False
pcv               False
wc                False
rc                False
htn               False
dm                False
cad               False
appet             False
pe                False
ane               False
classification    False
dtype: bool

In [30]:
x=data.iloc[:,1:25]

In [31]:
x

age    bp     sg   al   su     rbc        pc         pcc          ba  \
0    48.0  80.0  1.020  1.0  0.0  normal    normal  notpresent  notpresent   
1     7.0  50.0  1.020  4.0  0.0  normal    normal  notpresent  notpresent   
2    62.0  80.0  1.010  2.0  3.0  normal    normal  notpresent  notpresent   
3    48.0  70.0  1.005  4.0  0.0  normal  abnormal     present  notpresent   
4    51.0  80.0  1.010  2.0  0.0  normal    normal  notpresent  notpresent   
..    ...   ...    ...  ...  ...     ...       ...         ...         ...   
395  55.0  80.0  1.020  0.0  0.0  normal    normal  notpresent  notpresent   
396  42.0  70.0  1.025  0.0  0.0  normal    normal  notpresent  notpresent   
397  12.0  80.0  1.020  0.0  0.0  normal    normal  notpresent  notpresent   
398  17.0  60.0  1.025  0.0  0.0  normal    normal  notpresent  notpresent   
399  58.0  80.0  1.025  0.0  0.0  normal    normal  notpresent  notpresent   

            bgr  ...  hemo  pcv    wc   rc  htn   dm cad appet   pe  ane  
0    121.000000  ...  15.4   44  7800  5.2  yes  yes  no  good   no   no  
1    148.036517  ...  11.3   38  6000  5.2   no   no  no  good   no   no  
2    423.000000  ...   9.6   31  7500  5.2   no  yes  no  poor   no  yes  
3    117.000000  ...  11.2   32  6700  3.9  yes   no  no  poor  yes  yes  
4    106.000000  ...  11.6   35  7300  4.6   no   no  no  good   no   no  
..          ...  ...   ...  ...   ...  ...  ...  ...  ..   ...  ...  ...  
395  140.000000  ...  15.7   47  6700  4.9   no   no  no  good   no   no  
396   75.000000  ...  16.5   54  7800  6.2   no   no  no  good   no   no  
397  100.000000  ...  15.8   49  6600  5.4   no   no  no  good   no   no  
398  114.000000  ...  14.2   51  7200  5.9   no   no  no  good   no   no  
399  131.000000  ...  15.8   53  6800  6.1   no   no  no  good   no   no  

[400 rows x 24 columns]

In [32]:
x=data.iloc[:,1:25].values

In [33]:
x

array([[48.0, 80.0, 1.02, ..., 'good', 'no', 'no'],
       [7.0, 50.0, 1.02, ..., 'good', 'no', 'no'],
       [62.0, 80.0, 1.01, ..., 'poor', 'no', 'yes'],
       ...,
       [12.0, 80.0, 1.02, ..., 'good', 'no', 'no'],
       [17.0, 60.0, 1.025, ..., 'good', 'no', 'no'],
       [58.0, 80.0, 1.025, ..., 'good', 'no', 'no']], dtype=object)

In [34]:
y=data.iloc[:,25:].values

In [35]:
y

array([['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       ['ckd'],
       [

In [36]:
from sklearn.preprocessing import LabelEncoder

In [37]:
lb=LabelEncoder()

In [38]:
x[:,5]=lb.fit_transform(x[:,5])

In [39]:
x

array([[48.0, 80.0, 1.02, ..., 'good', 'no', 'no'],
       [7.0, 50.0, 1.02, ..., 'good', 'no', 'no'],
       [62.0, 80.0, 1.01, ..., 'poor', 'no', 'yes'],
       ...,
       [12.0, 80.0, 1.02, ..., 'good', 'no', 'no'],
       [17.0, 60.0, 1.025, ..., 'good', 'no', 'no'],
       [58.0, 80.0, 1.025, ..., 'good', 'no', 'no']], dtype=object)

In [40]:
x[:,6]=lb.fit_transform(x[:,6])

In [41]:
x[:,7]=lb.fit_transform(x[:,7])

In [42]:
x[:,8]=lb.fit_transform(x[:,8])

In [43]:
x[:,18]=lb.fit_transform(x[:,18])

In [44]:
x[:,19]=lb.fit_transform(x[:,19])

In [45]:
x[:,20]=lb.fit_transform(x[:,20])

In [46]:
x[:,21]=lb.fit_transform(x[:,21])

In [47]:
x[:,22]=lb.fit_transform(x[:,22])

In [48]:
x[:,23]=lb.fit_transform(x[:,23])

In [49]:
y[:,0]=lb.fit_transform(y[:,0])

In [50]:
x  #dataset.Age =dataset.Age.round()

array([[48.0, 80.0, 1.02, ..., 0, 0, 0],
       [7.0, 50.0, 1.02, ..., 0, 0, 0],
       [62.0, 80.0, 1.01, ..., 1, 0, 1],
       ...,
       [12.0, 80.0, 1.02, ..., 0, 0, 0],
       [17.0, 60.0, 1.025, ..., 0, 0, 0],
       [58.0, 80.0, 1.025, ..., 0, 0, 0]], dtype=object)

In [51]:
y

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
    

In [52]:
from sklearn.model_selection import train_test_split

In [53]:
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.2,random_state=0)

In [54]:
x_train

array([[25.0, 60.0, 1.02, ..., 0, 0, 0],
       [55.0, 80.0, 1.01, ..., 0, 0, 0],
       [35.0, 80.0, 1.005, ..., 0, 1, 0],
       ...,
       [51.48337595907928, 70.0, 1.02, ..., 0, 0, 0],
       [11.0, 80.0, 1.01, ..., 0, 0, 0],
       [62.0, 80.0, 1.01, ..., 0, 0, 0]], dtype=object)

In [55]:
y_train

array([[1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
    

In [56]:

from sklearn.preprocessing import StandardScaler

In [57]:
sc=StandardScaler()

In [58]:
x=sc.fit_transform(x)

ValueError: could not convert string to float: '?'

In [59]:
x

array([[48.0, 80.0, 1.02, ..., 0, 0, 0],
       [7.0, 50.0, 1.02, ..., 0, 0, 0],
       [62.0, 80.0, 1.01, ..., 1, 0, 1],
       ...,
       [12.0, 80.0, 1.02, ..., 0, 0, 0],
       [17.0, 60.0, 1.025, ..., 0, 0, 0],
       [58.0, 80.0, 1.025, ..., 0, 0, 0]], dtype=object)